# Production environment override
services:
  php:
    env_file:
      - .env
      - .env.local
      - .env.prod.local
    build:
      context: .
      target: frankenphp_prod
    environment:
      SERVER_NAME: ${SERVER_NAME}
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}

  # Message consumer for production
  messenger_consumer:
    env_file:
      - .env
      - .env.local
      - .env.prod.local
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
