<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260623060122 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE dwc_chronometric_age ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE dwc_chronometric_age ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dwc_event ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE dwc_event ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dwc_geological_context ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE dwc_geological_context ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dwc_identification ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE dwc_identification ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dwc_location ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE dwc_location ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dwc_material_entity ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE dwc_material_entity ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dwc_material_sample ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE dwc_material_sample ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dwc_measurement_or_fact ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE dwc_measurement_or_fact ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dwc_occurrence ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE dwc_occurrence ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dwc_organism ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE dwc_organism ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dwc_resource_relationship ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE dwc_resource_relationship ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dwc_taxon ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE dwc_taxon ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE easydb_object_type ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE easydb_object_type ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE job_status ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE job_status ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN job_status.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN job_status.completed_at IS \'\'');
        $this->addSql('ALTER TABLE occurrence_import ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE occurrence_import ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN occurrence_import.first_imported_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN occurrence_import.last_updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN occurrence_import.remote_last_updated_at IS \'\'');
        $this->addSql('ALTER TABLE "user" ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE "user" ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('DROP INDEX idx_75ea56e0fb7336f0');
        $this->addSql('DROP INDEX idx_75ea56e016ba31db');
        $this->addSql('DROP INDEX idx_75ea56e0e3bd61ce');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE messenger_messages ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'\'');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE dwc_chronometric_age ALTER id SET DEFAULT nextval(\'dwc_chronometric_age_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE dwc_chronometric_age ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE dwc_event ALTER id SET DEFAULT nextval(\'dwc_event_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE dwc_event ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE dwc_geological_context ALTER id SET DEFAULT nextval(\'dwc_geological_context_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE dwc_geological_context ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE dwc_identification ALTER id SET DEFAULT nextval(\'dwc_identification_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE dwc_identification ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE dwc_location ALTER id SET DEFAULT nextval(\'dwc_location_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE dwc_location ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE dwc_material_entity ALTER id SET DEFAULT nextval(\'dwc_material_entity_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE dwc_material_entity ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE dwc_material_sample ALTER id SET DEFAULT nextval(\'dwc_material_sample_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE dwc_material_sample ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE dwc_measurement_or_fact ALTER id SET DEFAULT nextval(\'dwc_measurement_or_fact_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE dwc_measurement_or_fact ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE dwc_occurrence ALTER id SET DEFAULT nextval(\'dwc_occurrence_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE dwc_occurrence ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE dwc_organism ALTER id SET DEFAULT nextval(\'dwc_organism_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE dwc_organism ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE dwc_resource_relationship ALTER id SET DEFAULT nextval(\'dwc_resource_relationship_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE dwc_resource_relationship ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE dwc_taxon ALTER id SET DEFAULT nextval(\'dwc_taxon_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE dwc_taxon ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE easydb_object_type ALTER id SET DEFAULT nextval(\'easydb_object_type_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE easydb_object_type ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE job_status ALTER id SET DEFAULT nextval(\'job_status_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE job_status ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN job_status.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN job_status.completed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('DROP INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750');
        $this->addSql('ALTER TABLE messenger_messages ALTER id SET DEFAULT nextval(\'messenger_messages_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE INDEX idx_75ea56e0fb7336f0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX idx_75ea56e016ba31db ON messenger_messages (delivered_at)');
        $this->addSql('CREATE INDEX idx_75ea56e0e3bd61ce ON messenger_messages (available_at)');
        $this->addSql('ALTER TABLE occurrence_import ALTER id SET DEFAULT nextval(\'occurrence_import_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE occurrence_import ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN occurrence_import.first_imported_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN occurrence_import.last_updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN occurrence_import.remote_last_updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE "user" ALTER id SET DEFAULT nextval(\'user_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE "user" ALTER id DROP IDENTITY');
    }
}
